version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5002
    depends_on:
      - backend
    networks:
      - portfolio-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///app.db
    volumes:
      - backend-data:/app/data
    networks:
      - portfolio-network

volumes:
  backend-data:

networks:
  portfolio-network:
    driver: bridge

